export const ODS_LIST = [
  { id: 1,  label: "Erradicação da Pobreza",       color: "#e5243b" },
  { id: 2,  label: "Fome Zero",                    color: "#dda63a" },
  { id: 3,  label: "Saúde e Bem-Estar",            color: "#4c9f38" },
  { id: 4,  label: "Educação de Qualidade",        color: "#c5192d" },
  { id: 5,  label: "Igualdade de Gênero",          color: "#ff3a21" },
  { id: 6,  label: "Água Potável e Saneamento",    color: "#26bde2" },
  { id: 7,  label: "Energia Acessível e Limpa",    color: "#fcc30b" },
  { id: 8,  label: "Trabalho e Crescimento",       color: "#a21942" },
  { id: 9,  label: "Indústria e Inovação",         color: "#fd6925" },
  { id: 10, label: "Redução das Desigualdades",    color: "#dd1367" },
  { id: 11, label: "Cidades Sustentáveis",         color: "#fd9d24" },
  { id: 12, label: "Consumo Responsável",          color: "#bf8b2e" },
  { id: 13, label: "Ação Climática",               color: "#3f7e44" },
  { id: 14, label: "Vida na Água",                 color: "#0a97d9" },
  { id: 15, label: "Vida Terrestre",               color: "#56c02b" },
  { id: 16, label: "Paz e Justiça",                color: "#00689d" },
  { id: 17, label: "Parcerias e Meios de Impl.",   color: "#19486a" },
];

export const AREAS = ["Saúde", "Tecnologia", "Educação", "Meio Ambiente", "Urbanismo", "Economia", "Segurança Pública", "Agro & Alimentação"];
export const TYPES = ["Aplicada", "Básica", "Extensão", "TCC", "Dissertação", "Tese"];
export const INSTITUTIONS = ["UFPE", "UNICAP", "CESAR School", "UFRPE", "UPE"];

export const UNIVERSITIES = [
  { value: "UFPE",          label: "UFPE — Universidade Federal de Pernambuco" },
  { value: "UFRPE",         label: "UFRPE — Universidade Federal Rural de Pernambuco" },
  { value: "UPE",           label: "UPE — Universidade de Pernambuco" },
  { value: "UNICAP",        label: "UNICAP — Universidade Católica de Pernambuco" },
  { value: "CESAR School",  label: "CESAR School" },
  { value: "IFPE",          label: "IFPE — Instituto Federal de Pernambuco" },
  { value: "UNINABUCO",     label: "UNINABUCO — Centro Universitário Maurício de Nassau" },
  { value: "FBV",           label: "FBV — Centro Universitário Wyden" },
  { value: "ESPM Recife",   label: "ESPM Recife" },
  { value: "Outra",         label: "Outra instituição" },
];

export const RESEARCHERS = [
  { id: 1, name: "Dra. Ana Lima",        institution: "UFPE",        avatar: "AL", area: "Saúde" },
  { id: 2, name: "Prof. Carlos Mendes",  institution: "CESAR School", avatar: "CM", area: "Tecnologia" },
  { id: 3, name: "Dr. Fábio Torres",     institution: "UNICAP",      avatar: "FT", area: "Urbanismo" },
  { id: 4, name: "Profa. Rita Souza",    institution: "UFPE",        avatar: "RS", area: "Educação" },
  { id: 5, name: "Dr. Paulo Neves",      institution: "UFRPE",       avatar: "PN", area: "Agro & Alimentação" },
  { id: 6, name: "Dra. Mariana Costa",   institution: "UPE",         avatar: "MC", area: "Meio Ambiente" },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Detecção Precoce de Dengue via Análise de Dados Climáticos",
    institution: "UFPE",
    area: "Saúde",
    type: "Aplicada",
    keywords: ["dengue", "saúde pública", "machine learning", "dados climáticos"],
    ods: [3, 11, 13],
    status: "published",
    researcher: RESEARCHERS[0],
    abstract: "Esta pesquisa propõe um modelo preditivo baseado em aprendizado de máquina para identificar surtos de dengue com antecedência mínima de 4 semanas, utilizando correlações entre variáveis climáticas (temperatura, precipitação, umidade) e séries históricas de notificações epidemiológicas no município de Recife entre 2010–2023.",
    simplified: "Criamos um sistema inteligente que avisa com até 4 semanas de antecedência onde podem surgir focos de dengue em Recife. O sistema analisa dados de clima — como chuva e temperatura — e históricos de casos da cidade para fazer essa previsão. Com isso, agentes de saúde podem agir antes dos surtos acontecerem.",
    year: 2024,
    views: 312,
    connections: 5,
    tags: ["IA", "Epidemiologia"],
  },
  {
    id: 2,
    title: "Plataforma de Monitoramento de Qualidade do Ar em Tempo Real",
    institution: "CESAR School",
    area: "Meio Ambiente",
    type: "Aplicada",
    keywords: ["qualidade do ar", "IoT", "sensores", "poluição"],
    ods: [11, 13, 3],
    status: "published",
    researcher: RESEARCHERS[1],
    abstract: "Desenvolvimento de uma rede distribuída de sensores IoT de baixo custo para monitoramento contínuo de material particulado (PM2.5, PM10) e gases poluentes (NOx, CO) nas principais vias e bairros de Recife, com dashboard público de acesso aberto.",
    simplified: "Instalamos pequenos sensores espalhados por Recife que medem a qualidade do ar 24 horas por dia. Os dados ficam disponíveis para qualquer pessoa consultar em tempo real, mostrando em quais bairros o ar está mais poluído. Isso ajuda moradores e o poder público a tomarem decisões mais informadas sobre mobilidade e saúde.",
    year: 2024,
    views: 198,
    connections: 3,
    tags: ["IoT", "Smart City"],
  },
  {
    id: 3,
    title: "Requalificação Urbana e Habitação Social no Coque",
    institution: "UNICAP",
    area: "Urbanismo",
    type: "Extensão",
    keywords: ["habitação", "urbanismo", "comunidade", "coque"],
    ods: [1, 10, 11],
    status: "published",
    researcher: RESEARCHERS[2],
    abstract: "Pesquisa-ação que avalia os impactos socioespaciais das intervenções de requalificação urbana no bairro do Coque, mapeando tensões entre o processo de modernização da orla do Recife e a permanência das comunidades históricas.",
    simplified: "Estudamos as mudanças que estão acontecendo no bairro do Coque, em Recife, e como elas afetam as famílias que vivem lá há gerações. Queremos entender o que pode ser feito para que as melhorias na cidade não expulsem as comunidades tradicionais de seus próprios bairros.",
    year: 2023,
    views: 145,
    connections: 2,
    tags: ["Comunidade", "Habitação"],
  },
  {
    id: 4,
    title: "Gamificação no Ensino de Matemática em Escolas Públicas do Recife",
    institution: "UFPE",
    area: "Educação",
    type: "Dissertação",
    keywords: ["gamificação", "matemática", "ensino público", "engajamento"],
    ods: [4, 10],
    status: "published",
    researcher: RESEARCHERS[3],
    abstract: "Investigação sobre o impacto da introdução de elementos de gamificação — pontos, conquistas, rankings — no aprendizado e engajamento de alunos do 6º ao 9º ano em escolas da rede pública municipal de Recife, com controle randomizado entre turmas.",
    simplified: "Testamos o uso de jogos e dinâmicas divertidas (como pontuação e conquistas) nas aulas de matemática de escolas públicas do Recife. O objetivo é descobrir se isso ajuda os alunos a aprenderem mais e a se interessarem mais pela matéria, especialmente nas turmas do ensino fundamental.",
    year: 2023,
    views: 267,
    connections: 7,
    tags: ["EdTech", "Escola Pública"],
  },
  {
    id: 5,
    title: "Agricultura Urbana e Segurança Alimentar em Periferias de Recife",
    institution: "UFRPE",
    area: "Agro & Alimentação",
    type: "Aplicada",
    keywords: ["agricultura urbana", "segurança alimentar", "periferias", "hortas comunitárias"],
    ods: [2, 1, 11],
    status: "published",
    researcher: RESEARCHERS[4],
    abstract: "Avaliação do potencial de hortas comunitárias e telhados verdes em zonas periurbanas de Recife para contribuir com a segurança alimentar e geração de renda, incluindo análise de viabilidade econômica e modelos de gestão participativa.",
    simplified: "Estamos estudando como hortas comunitárias em bairros periféricos do Recife podem ajudar famílias a terem acesso a alimentos frescos e ainda gerar renda extra. Avaliamos quais espaços da cidade podem receber essas hortas e como as próprias comunidades podem gerir esses projetos.",
    year: 2024,
    views: 89,
    connections: 1,
    tags: ["Comunidade", "Alimentação"],
  },
  {
    id: 6,
    title: "Análise de Risco de Alagamentos com Visão Computacional em Drones",
    institution: "CESAR School",
    area: "Segurança Pública",
    type: "Aplicada",
    keywords: ["alagamentos", "drones", "visão computacional", "defesa civil"],
    ods: [11, 13, 16],
    status: "published",
    researcher: RESEARCHERS[1],
    abstract: "Desenvolvimento de pipeline de visão computacional aplicado a imagens aéreas coletadas por drones para mapeamento e classificação automática de áreas de risco de alagamento em Recife, com integração à plataforma de Defesa Civil municipal.",
    simplified: "Usamos drones e inteligência artificial para identificar automaticamente as áreas de Recife com maior risco de alagamento. As imagens captadas pelos drones são analisadas por um sistema que aprende a reconhecer padrões de risco. Os resultados são integrados diretamente ao sistema da Defesa Civil da cidade.",
    year: 2024,
    views: 421,
    connections: 9,
    tags: ["IA", "Segurança"],
  },
];

export const MESSAGES = [
  {
    id: 1,
    projectId: 1,
    orgName: "Secretaria Municipal de Saúde",
    orgAvatar: "SS",
    messages: [
      { from: "org",        text: "Olá, Dra. Ana! Vimos sua pesquisa sobre detecção de dengue e ficamos muito interessados. Gostaríamos de conversar sobre uma possível parceria com a Vigilância Epidemiológica.", time: "09:14" },
      { from: "researcher", text: "Boa tarde! Fico muito feliz com o interesse. O sistema já está em fase de validação e acredito que uma integração com os dados da secretaria seria extremamente valiosa para melhorar a precisão.", time: "10:32" },
      { from: "org",        text: "Exatamente. Temos uma base histórica de 15 anos de notificações. Poderíamos agendar uma reunião esta semana para apresentar os dados e discutir os próximos passos?", time: "10:45" },
    ],
  },
  {
    id: 2,
    projectId: 6,
    orgName: "Defesa Civil do Recife",
    orgAvatar: "DC",
    messages: [
      { from: "org",        text: "Prof. Carlos, sua pesquisa com drones para mapeamento de alagamentos é exatamente o que precisamos. Temos cobertura de todas as zonas críticas da cidade.", time: "14:00" },
      { from: "researcher", text: "Ótimo! Já trabalhamos com dados de algumas dessas áreas. Uma integração formal nos permitiria cobrir toda a cidade em tempo real.", time: "14:38" },
    ],
  },
];

export const MY_PROJECTS = [
  { ...PROJECTS[0], status: "published" },
  { ...PROJECTS[5], status: "published" },
  {
    id: 99,
    title: "Predição de Evasão Escolar com NLP em Dados Socioeconômicos",
    institution: "UFPE",
    area: "Educação",
    type: "Tese",
    keywords: ["evasão escolar", "NLP", "dados socioeconômicos"],
    ods: [4, 1, 10],
    status: "review",
    researcher: RESEARCHERS[0],
    year: 2025,
    views: 0,
    connections: 0,
    tags: ["IA", "Educação"],
  },
  {
    id: 100,
    title: "Análise de Sentimento em Redes Sociais para Monitoramento de Epidemias",
    institution: "UFPE",
    area: "Saúde",
    type: "Aplicada",
    keywords: ["redes sociais", "epidemias", "sentimento"],
    ods: [3, 9],
    status: "draft",
    researcher: RESEARCHERS[0],
    year: 2025,
    views: 0,
    connections: 0,
    tags: ["IA", "Saúde"],
  },
];
